services:


  mysql:

    image: mysql:8.4


    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: appdb


    volumes:

      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql


    ports:

      - "3306:3306"


  php:

    build: .


    ports:

      - "8080:80"


    depends_on:

      - mysql


    volumes:

      - .:/var/www/html
 